services:
  mongodb:
    image: mongo:7
    container_name: exan-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=exan
    volumes:
      - mongodb_data:/data/db
      #! The script below might not be required with the latest version of the app that allows to create the user and database on the fly, but it is kept here for backward compatibility.
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 
    restart: unless-stopped

  inference:
    build: ./inference
    container_name: exan-inference
    ports:
      - "8000:8000"
    env_file:
      - path: ./inference/.env
        required: false
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./inference/app:/app/app
    #! I dont think we need a dependency here but for the auth-server to work we need to have the mongodb up and running
    depends_on:
      - mongodb
    restart: unless-stopped

  auth-server:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: exan-auth-server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://exan_app:exan_app_password@mongodb:27017/exan?authSource=exan
      #! is this actually necessary?
      - JWT_SECRET=${JWT_SECRET:-change-this-to-a-random-secret}
    depends_on:
      - mongodb
    restart: unless-stopped

  webapp:
    build: ./webapp
    container_name: exan-webapp
    ports:
      - "3000:80"
    depends_on:
      - inference
      - auth-server
    restart: unless-stopped

volumes:
  mongodb_data:
