#!/usr/bin/env node
// Generates src-tauri/windows/models.nsh (the model choice page of the NSIS installer) from the engine's
// model catalog, so the installer always offers exactly the models the app can download.
//
//   node scripts/installer-models.mjs          write the file
//   node scripts/installer-models.mjs --check  fail if the committed file is out of date (npm run check)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { fail, root } from "./lib.mjs";

const catalog = JSON.parse(readFileSync(join(root, "sidecar", "exan_sidecar", "engine", "models.json"), "utf8"));
const target = join(root, "src-tauri", "windows", "models.nsh");

/** Escapes text for an NSIS string: `$` and `"` are special, everything else is kept (the script is Unicode). */
const escape = (text) => String(text).replace(/\$/g, "$$$$").replace(/"/g, '$\\"').replace(/\r?\n/g, " ");
const nsis = (text) => `"${escape(text)}"`;
const size = (bytes) => (bytes >= 1e9 ? `${(bytes / 1e9).toFixed(1)} GB` : `${Math.round(bytes / 1e6)} MB`);

const models = catalog.models;
if (!models.length) fail("models.json lists no models");
// Layout of the page in dialog units (the MUI page body is about 300 x 140 units).
const top = 20;
const rowHeight = 22;
const skipY = top + models.length * rowHeight;
const consentY = skipY + 14;

const lines = [
  "; Generated by scripts/installer-models.mjs from sidecar/exan_sidecar/engine/models.json - do not edit.",
  "; Used by windows/hooks.nsh (the reading-model page of the installer).",
  "",
  `!define EXAN_SKIP_Y ${skipY}u`,
  `!define EXAN_CONSENT_Y ${consentY}u`,
  "",
  ...models.map((_, index) => `Var ExanModelRadio${index}`),
  "",
  "!macro EXAN_MODEL_RADIOS",
];
models.forEach((model, index) => {
  const y = top + index * rowHeight;
  const bytes = model.files.reduce((sum, file) => sum + file.size, 0);
  const label = `${escape(`${model.label} (${model.params}, ${size(bytes)})`)}${model.recommended ? " $(exanRecommended)" : ""}`;
  lines.push(
    `  \${NSD_CreateRadioButton} 0 ${y}u 100% 10u "${label}"`,
    `  Pop $ExanModelRadio${index}`,
    `  \${NSD_CreateLabel} 13u ${y + 10}u 287u 10u "$(exanModelSummary${index})"`,
    "  Pop $0",
  );
});
lines.push("!macroend", "", "; Checks the radio of model id ${ID} (no-op for unknown ids).", "!macro EXAN_MODEL_CHECK ID");
models.forEach((model, index) => {
  lines.push(`  \${If} \${ID} == ${nsis(model.id)}`, `    \${NSD_Check} $ExanModelRadio${index}`, "  ${EndIf}");
});
lines.push("!macroend", "", `!define EXAN_RECOMMENDED_MODEL ${nsis(models.find((m) => m.recommended)?.id ?? models[0].id)}`, "");
lines.push("; Sets ${VAR} to the id of the checked model, or to an empty string.", "!macro EXAN_MODEL_SELECTED VAR", '  StrCpy ${VAR} ""');
models.forEach((model, index) => {
  lines.push(`  \${NSD_GetState} $ExanModelRadio${index} $0`, "  ${If} $0 == ${BST_CHECKED}", `    StrCpy \${VAR} ${nsis(model.id)}`, "  ${EndIf}");
});
lines.push("!macroend", "", "; Expanded after the languages are loaded (see installer.nsi).", "!macro EXAN_MODEL_LANG_STRINGS");
models.forEach((model, index) => {
  lines.push(`  LangString exanModelSummary${index} \${LANG_ENGLISH} ${nsis(model.summary.en)}`);
  lines.push("  !ifdef LANG_GERMAN", `    LangString exanModelSummary${index} \${LANG_GERMAN} ${nsis(model.summary.de ?? model.summary.en)}`, "  !endif");
});
lines.push("!macroend", "");
const content = lines.join("\r\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // missing file
  }
  if (current !== content) fail("src-tauri/windows/models.nsh is out of date. Run `npm run installer:models` and commit it.");
  console.log("Installer model page is up to date.");
} else {
  writeFileSync(target, content);
  console.log(`✔ ${models.length} models → ${target}`);
}
