; Generated by scripts/installer-models.mjs from sidecar/exan_sidecar/engine/models.json - do not edit.
; Used by windows/hooks.nsh (the reading-model page of the installer).

!define EXAN_SKIP_Y 86u
!define EXAN_CONSENT_Y 100u

Var ExanModelRadio0
Var ExanModelRadio1
Var ExanModelRadio2

!macro EXAN_MODEL_RADIOS
  ${NSD_CreateRadioButton} 0 20u 100% 10u "Granite-Docling 258M (258M, 282 MB) $(exanRecommended)"
  Pop $ExanModelRadio0
  ${NSD_CreateLabel} 13u 30u 287u 10u "$(exanModelSummary0)"
  Pop $0
  ${NSD_CreateRadioButton} 0 42u 100% 10u "PaddleOCR-VL 1.6 (0.9B, 1.8 GB)"
  Pop $ExanModelRadio1
  ${NSD_CreateLabel} 13u 52u 287u 10u "$(exanModelSummary1)"
  Pop $0
  ${NSD_CreateRadioButton} 0 64u 100% 10u "Qwen2.5-VL 3B (3B, 2.8 GB)"
  Pop $ExanModelRadio2
  ${NSD_CreateLabel} 13u 74u 287u 10u "$(exanModelSummary2)"
  Pop $0
!macroend

; Checks the radio of model id ${ID} (no-op for unknown ids).
!macro EXAN_MODEL_CHECK ID
  ${If} ${ID} == "granite-docling-258m"
    ${NSD_Check} $ExanModelRadio0
  ${EndIf}
  ${If} ${ID} == "paddleocr-vl-1.6"
    ${NSD_Check} $ExanModelRadio1
  ${EndIf}
  ${If} ${ID} == "qwen2.5-vl-3b"
    ${NSD_Check} $ExanModelRadio2
  ${EndIf}
!macroend

!define EXAN_RECOMMENDED_MODEL "granite-docling-258m"

; Sets ${VAR} to the id of the checked model, or to an empty string.
!macro EXAN_MODEL_SELECTED VAR
  StrCpy ${VAR} ""
  ${NSD_GetState} $ExanModelRadio0 $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy ${VAR} "granite-docling-258m"
  ${EndIf}
  ${NSD_GetState} $ExanModelRadio1 $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy ${VAR} "paddleocr-vl-1.6"
  ${EndIf}
  ${NSD_GetState} $ExanModelRadio2 $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy ${VAR} "qwen2.5-vl-3b"
  ${EndIf}
!macroend

; Expanded after the languages are loaded (see installer.nsi).
!macro EXAN_MODEL_LANG_STRINGS
  LangString exanModelSummary0 ${LANG_ENGLISH} "Smallest and fastest; best with printed or typed answers"
  !ifdef LANG_GERMAN
    LangString exanModelSummary0 ${LANG_GERMAN} "Am kleinsten und schnellsten; am besten bei gedruckten Antworten"
  !endif
  LangString exanModelSummary1 ${LANG_ENGLISH} "Small OCR model that also reads handwriting"
  !ifdef LANG_GERMAN
    LangString exanModelSummary1 ${LANG_GERMAN} "Kleines OCR-Modell, liest auch Handschrift"
  !endif
  LangString exanModelSummary2 ${LANG_ENGLISH} "General vision model; licence for research and evaluation only"
  !ifdef LANG_GERMAN
    LangString exanModelSummary2 ${LANG_GERMAN} "Allgemeines Bildmodell; Lizenz nur für Forschung und Erprobung"
  !endif
!macroend
